name: "Jira Check"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  publish:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v1
   - uses: deepakputhraya/action-pr-title@master
     with:
       # Match pull request titles in the form UI-1234 - Message.
       regex: '(ADMIN|CA|COM|DEX|ESHD|HACK|INF|LC|RUN|SL|SRV|WEB)-\d+'
